[project]
name = "ml2"
version = "0.1.0"
description = "DruhÃ¡ ML hodina - knihovna scikit-lean"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
]
